### PR TITLE
refactor: use `plugin.onLoad`

### PR DESCRIPTION
**Pull request by MicroCBer**

### CODE REVIEW

**Comment by MicroCBer** [comment]
btw I'm going to add this into [plugin market](https://gitee.com/microblock/better-ncm-v2-data/tree/master/plugin_market) to allow more people to enjoy this. if you are against this, please tell me

**Comment by solstice23** [comment]
Yes, but adding to the gitee is kind of cumbersome for me because I rarely use it. Maybe we can automatically sync it to the market?

**Comment by MicroCBer** [comment]
I'm taking consideration to make a GitHub action to automate the process of releasing and updating the plugins as it's also not an easy operation for me.

**Comment by MicroCBer** [comment]
(the usage of gitee is just for better connectivity in China Mainland then there'll be fewer people asking me why they can't use the plugin)

**Comment by solstice23** [comment]
Before that, you can upload it to the market first. The releases are not the latest so please directly clone the repo. I'm going to add something new like particle effect, but I don't know when.

**Comment by solstice23** [comment]
I have an idea that using github as the main market repository and syncing it to the gitee.

**Comment by solstice23** [comment]
Btw I also want to implement a visualizer but I don't know how to get the audio buffer data.

**Comment by MicroCBer** [comment]
> Btw I also want to implement a visualizer but I don't know how to get the audio buffer data.

NCM plays music in the CPP layer... we'll probably need to have some more hooks in order to do that. I'll get deeper into it next week if I can get back home...

**Comment by MicroCBer** [comment]
> I have an idea that using github as the main market repository and syncing it to the gitee.

uh, nice idea, it will also be easier for me to make the gh action

**Comment by Steve-xmh** [comment]
> Btw I also want to implement a visualizer but I don't know how to get the audio buffer data.

有一个比较偏门但是理论可行的办法：直接调用自己下载音乐然后和播放器同步进度播放，通过浏览器的API获取傅里叶变化数据

一部分获取代码参考：

```typescript
/**
 * 根据歌曲 ID 获取歌曲文件下载链接
 * @param songId 歌曲ID
 * @param byterate 音质码率，默认最高
 * @returns 歌词数据信息
 */
export function getMusicURL(songId: number, byterate: number = 999000): Promise<EAPILyricResponse> {
	// eapiRequest 函数取自 window.nej.j.$e
	// 参考 orpheus://orpheus/pub/core.e5842f1.js?d7496bf6377403c83793c37f6fbf0300:formatted:5158
	return new Promise((resolve, reject) => {
		eapiRequest(`${APP_CONF.domain}/api/song/enhance/download/url`, {
			method: 'POST',
			type: "json",
			data: {
				id: songId,
				br: byterate
			},
			onload: resolve,
			onerror: reject,
		});
	});
}
```

**Pull request merged**
